services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER_LOCAL}
      - POSTGRES_PASSWORD=${POSTGRES_PW_LOCAL}
      - POSTGRES_DB=${POSTGRES_DB_LOCAL} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL_LOCAL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW_LOCAL}
    ports:
      - "5050:80"
    restart: always
