-- CreateTable
CREATE TABLE "L100FlightData" (
    "id" TEXT NOT NULL,
    "contact" TEXT NOT NULL,
    "station" TEXT NOT NULL,
    "stationHeight" TEXT NOT NULL,
    "latitude" TEXT NOT NULL,
    "longitude" TEXT NOT NULL,
    "flightNum" TEXT NOT NULL,
    "launchDate" TEXT NOT NULL,
    "launchTime" TEXT NOT NULL,
    "radiosondeType" TEXT NOT NULL,
    "radiosondeNum" TEXT NOT NULL,
    "o3SondeId" TEXT NOT NULL,
    "background" TEXT NOT NULL,
    "flowrate" TEXT NOT NULL,
    "rhCorr" TEXT NOT NULL,
    "sondeTotalO3DU" TEXT NOT NULL,
    "sondeTotalO3SBUV" TEXT NOT NULL,
    "data" TEXT NOT NULL,
    "created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "L100FlightData_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RawFlightData" (
    "id" TEXT NOT NULL,
    "station" TEXT NOT NULL,
    "headerLines" TEXT NOT NULL,
    "dataColumns" TEXT NOT NULL,
    "flightNumber" TEXT NOT NULL,
    "dateGMT" TEXT NOT NULL,
    "timeGMT" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "longitude" TEXT NOT NULL,
    "latitude" TEXT NOT NULL,
    "launchAltitudeKm" TEXT NOT NULL,
    "surfacePressureMb" TEXT NOT NULL,
    "surfaceTempDeg" TEXT NOT NULL,
    "surfaceHumidity" TEXT NOT NULL,
    "trop1AltitudeKm" TEXT NOT NULL,
    "trop2AltitudeKm" TEXT NOT NULL,
    "turnAltitudeKm" TEXT NOT NULL,
    "turnPressureMb" TEXT NOT NULL,
    "radiosondeNumber" TEXT NOT NULL,
    "humicapSensor" TEXT NOT NULL,
    "radiationCorrection" TEXT NOT NULL,
    "pressureSensorOffset" TEXT NOT NULL,
    "geomPressOffsetCorr" TEXT NOT NULL,
    "radiosondeTotalColWater" TEXT NOT NULL,
    "instrumentType" TEXT NOT NULL,
    "originalFileSource" TEXT NOT NULL,
    "ozoneSondeNumber" TEXT NOT NULL,
    "solution" TEXT NOT NULL,
    "oltmansSolutionCorrection" TEXT NOT NULL,
    "oltmansTermA" TEXT NOT NULL,
    "oltmansTermB" TEXT NOT NULL,
    "ozonePumpTempCorrection" TEXT NOT NULL,
    "totalOzoneColumnCMR" TEXT NOT NULL,
    "totalOzoneColumnSBUV" TEXT NOT NULL,
    "totalOzoneStopPressure" TEXT NOT NULL,
    "timeToPump100Ml" TEXT NOT NULL,
    "dryFlowrateCorrection" TEXT NOT NULL,
    "cellBackgroundIB2" TEXT NOT NULL,
    "backgroundCurrent" TEXT NOT NULL,
    "coefficients" TEXT NOT NULL,
    "pumpCoefficientPC0" TEXT NOT NULL,
    "pumpCoefficientPC1" TEXT NOT NULL,
    "pumpCoefficientPC2" TEXT NOT NULL,
    "pumpCoefficientPC3" TEXT NOT NULL,
    "adSystem" TEXT NOT NULL,
    "flowrateCorrType" TEXT NOT NULL,
    "pressureDataSource" TEXT NOT NULL,
    "altitudeDataSource" TEXT NOT NULL,
    "geoAltAnchoringMethod" TEXT NOT NULL,
    "data" JSONB NOT NULL,
    "created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RawFlightData_pkey" PRIMARY KEY ("id")
);
